version: "3.8"

services:
  webapp:
    build:
      context: ./webapp
      target: dev
    image: "${COMPOSE_PROJECT_NAME}_webapp:dev"
    ports:
      - 5173:5173
    volumes:
      - ./webapp/app:/app
